apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devos-api
  namespace: devos
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: devos-api
  namespaceSelector:
    matchNames:
      - devos
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
